---
- name: Golang
  tags:
    - go
    - golang
  block:
    - name: Remove system golang
      become: yes
      ansible.builtin.package:
        name:
          - golang
        state: absent

    - name: Install Golang
      include_role:
        name: gantsign.golang

    - name: Create /opt/go/current symlink
      become: yes
      ansible.builtin.file:
        src: "{{ ansible_local.golang.general.home }}"
        dest: /opt/go/current
        force: yes
        owner: root
        group: root
        state: link
