---
- name: Install lua v5.1
  homebrew:
    name: lua@5.1
    state: "{{ package_state }}"

- name: Install openresty
  homebrew:
    name: openresty/brew/openresty
    state: "{{ package_state }}"

- name: Install lua packages
  shell: "luarocks-5.1 install {{ item }}"
  loop:
    - busted
    - luacov
    - luafilesystem
    - lua-cjson
    - lua-resty-http
    - lua-resty-jwt
