---
all:
  hosts:
    badger:
      ansible_host: badger.serenity
    haven:
      ansible_host: haven.serenity
    jayne:
      ansible_host: jayne.serenity
      install_docker: true
    mal:
      ansible_host: mal.serenity
    yosafbridge:
      ansible_host: yosafbridge.serenity
  vars:
    bootstrap_user: bschwedler
    package_state: present
  children:
    backup:
      mal:
    desktop:
      hosts:
        jayne:
        mal:
        yosafbridge:
      children:
        media:
          hosts:
            mal:
            yosafbridge:
    dev:
      hosts:
        badger:
        jayne:
        mal:
      children:
        rstudio:
          hosts:
            badger:
            jayne:
    hypervisors:
      hosts:
        jayne:
