---
- name: "C++"
  tags:
    - cpp
    - c++
  become: yes
  block:
    - name: Install gcc - RedHat Family
      when: ansible_os_family == 'RedHat'
      ansible.builtin.package:
        name:
          - gcc
          - gcc-c++
        state: "{{ package_state }}"

    - name: Install build-essential - Debian Family
      when: ansible_os_family == 'Debian'
      ansible.builtin.package:
        name:
          - build-essential

    - name: Install LLVM clang
      ansible.builtin.package:
        name:
          - clang
        state: "{{ package_state }}"

    - name: Install cmake
      ansible.builtin.package:
        name:
          - cmake
        state: "{{ package_state }}"

    - name: Development Libraries - RedHat Family
      when: ansible_os_family == 'RedHat'
      ansible.builtin.package:
        name:
          - bzip2-devel
          - libuser-devel
          - libuuid-devel
          - openssl-devel
          - zlib-devel
        state: "{{ package_state }}"

    - name: Development Libraries - Debian Family
      when: ansible_os_family == 'Debian'
      ansible.builtin.package:
        name:
          - libacl1-dev
          - libattr1-dev
          - libbz2-dev
          - libcap-dev
          - libcurl4-openssl-dev
          - libegl1-mesa
          - libfuse2
          - libgl1-mesa-dev
          - libglib2.0-dev
          - libgtk-3-0
          - libnss3
          - libssl-dev
          - libuser1-dev
          - libxml2-dev
          - libxslt1-dev
        state: "{{ package_state }}"

- name: Boost
  tags:
    - cpp
    - c++
    - boost
  become: yes
  block:
    - name: Boost Libraries - RedHat Family
      when: ansible_os_family == 'RedHat'
      block:
        - name: Boost Development
          ansible.builtin.package:
            name:
              - boost-devel
            state: "{{ package_state }}"

    - name: Boost Libraries - Debian Family
      when: ansible_os_family == 'Debian'
      block:
        - name: Boost Development
          ansible.builtin.package:
            name:
              - libboost-dev
              - libboost-all-dev
            state: "{{ package_state }}"
