---
- name: Install postgres
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - postgresql

- name: Install mysql
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - mysql

- name: Install mongodb
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - mongodb

- name: Install influxdb
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - influxdb
