---
- name: Install postgres
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - postgresql

- name: Install mysql
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - mysql

- name: Install mongodb and tools
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - mongodb
    - robo-3t

- name: Install influxdb
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - influxdb

- name: Install redis
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - redis

- name: Install sqlite
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - sqlite
