---
- import_tasks: osx.yaml
  when: ansible_os_family|lower == 'darwin'

- name: Install Ansible
  pip:
    name:
      - ansible
    executable: /usr/local/bin/pip3
    extra_args: "--prefix=/usr/local"
    state: "{{ package_state }}"
  become: "{{ ansible_os_family|lower != 'darwin' }}"

- name: Install VirtualEnv tools
  pip:
    name:
      - virtualenv
      - virtualenv-clone
      - virtualenvwrapper
    executable: /usr/local/bin/pip3
    state: "{{ package_state }}"
  become: "{{ ansible_os_family|lower != 'darwin' }}"

- name: Install testing tools
  pip:
    name:
      - flake8
      - pycodestyle
      - pylint
      - pytest
      - pytest-flake8
      - pytest-pycodestyle
      - pytest-pylint
    executable: /usr/local/bin/pip3
    state: "{{ package_state }}"
  become: "{{ ansible_os_family|lower != 'darwin' }}"

- import_tasks: watcher.yaml
  when: ansible_os_family|lower == 'darwin'
