---
- name: Install python2 libraries
  pip:
    name:
      - b2
    executable: pip2
    state: "{{ package_state }}"

- name: Install python3 libraries
  pip:
    name:
      - b2
    executable: /usr/local/bin/pip3
    state: "{{ package_state }}"

- name: Install duply
  dnf:
    name:
      - duplicity
      - duply
    state: "{{ package_state }}"
