---
- name: Install python3 libraries
  ansible.builtin.pip:
    name:
      - b2
    executable: /usr/local/bin/pip3
    state: "{{ package_state }}"

- name: Install duplicity
  ansible.builtin.dnf:
    name:
      - duplicity
    state: "{{ package_state }}"
