---
- name: Install shell utilities
  ansible.builtin.dnf:
    name:
      - screen
      - curl
      - rsync
      - telnet
      - tmux
      - tree
      - wget
    state: "{{ package_state }}"

- name: Install git and helpers
  ansible.builtin.dnf:
    name:
      - git
      - tig
    state: "{{ package_state }}"

- name: Install vim
  ansible.builtin.dnf:
    name:
      - vim
      - neovim
    state: "{{ package_state }}"

- name: Install additional CLI utilities
  ansible.builtin.dnf:
    name:
      - ack
      - jq
      - httpie
      - openvpn
      - perl
      - pwgen
      - speedtest-cli
    state: "{{ package_state }}"

- name: Enable bcotton/cherrytree COPR
  community.general.copr:
    state: enabled
    name: bcotton/cherrytree

- name: Install cherrytree
  ansible.builtin.dnf:
    name: cherrytree-future
    state: "{{ package_state }}"
