---
- name: Install shell utilities
  dnf:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - screen
    - curl
    - rsync
    - telnet
    - tmux
    - tree
    - wget

- name: Install git and helpers
  dnf:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - git
    - tig

- name: Install vim
  dnf:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - vim
    - neovim

- name: Install additional CLI utilities
  dnf:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - ack
    - jq
    - httpie
    - openvpn
    - perl
    - pwgen
    - speedtest-cli
