---
- name: Install GNU utilities
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - coreutils
    - findutils
    - gnu-tar
    - gnu-sed
    - gawk
    - gnutls
    - gnu-indent
    - gnu-getopt
    - gnu-which

- name: Symlink GNU utilities
  file:
    src: "/usr/local/bin/g{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  loop:
    - awk
    - find
    - indent
    - sed
    - tar
    - which
    - xargs

- name: Install Shell
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - bash
    - tmux

- name: Install iterm2
  homebrew_cask:
    name: iterm2
    state: "{{ package_state_cask }}"

- name: Install shell utilities
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - pstree
    - psgrep
    - screen
    - curl
    - rsync
    - telnet
    - tree
    - watch
    - wget

- name: Tap git-duet/tap
  homebrew_tap:
    name: git-duet/tap
    state: present

- name: Install git and helpers
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - git
    - tig
    - git-duet

- name: Install vim
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - vim
    - neovim

- name: Install additional CLI utilities
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - ack
    - cadaver
    - dos2unix
    - jq
    - httpie
    - lastpass-cli
    - lftp
    - openvpn
    - perl
    - pwgen
    - speedtest-cli
    - vault

- name: Install cloud CLI tools
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - awscli
    - s3cmd

- name: Install cloud CLI casks
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - google-cloud-sdk

- name: Install build tools
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - autoconf
    - automake
    - cdrtools

- name: Tap caskroom/versions
  homebrew_tap:
    name: caskroom/versions
    state: present

- name: Install Browers
  homebrew_cask:
    name: "{{ item }}"
    state: "{{ package_state_cask }}"
  loop:
    - firefox
    - firefox-developer-edition
    - google-chrome

- name: Install Tunnelblick
  homebrew_cask:
    name: tunnelblick
    state: "{{ package_state_cask }}"

- name: Install Citrix Tools
  homebrew_cask:
    name: "{{ item }}"
    state: "{{ package_state_cask }}"
  loop:
    - citrix-receiver
    - citrix-workspace
  ignore_errors: true

- name: Install postman
  homebrew_cask:
    name: postman
    state: "{{ package_state_cask }}"

- name: Install communication tools
  homebrew_cask:
    name: "{{ item }}"
    state: "{{ package_state_cask }}"
  loop:
    - discord
    - microsoft-teams
    - slack
    - skype
    - skype-for-business

- name: Install OSX productivity tools
  homebrew_cask:
    name: "{{ item }}"
    state: "{{ package_state_cask }}"
  loop:
    - alfred
    - authy
    - flux
    - flycut
    - grandperspective
    - itsycal
    - lastpass
    - spectacle
