---
- name: Install GNU utilities
  homebrew:
    name: "{{ item }}"
    install_options: with-default-names
    state: "{{ package_state }}"
  with_items:
    - coreutils
    - findutils
    - gnu-tar
    - gnu-sed
    - gawk
    - gnutls
    - gnu-indent
    - gnu-getopt

- name: Install Shell
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  with_items:
    - bash
    - tmux

- name: Install iterm2
  homebrew_cask:
    name: iterm2
    state: "{{ package_state }}"

- name: Install shell utilities
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  with_items:
    - pstree
    - psgrep
    - screen
    - curl
    - rsync
    - telnet
    - tree
    - watch
    - wget

- name: Install git and helpers
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  with_items:
    - git
    - tig

- name: Install vim
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  with_items:
    - vim
    - neovim

- name: Install additional CLI utilities
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  with_items:
    - ack
    - jq
    - httpie
    - openvpn
    - perl
    - pwgen
    - speedtest-cli
    - vault

- name: Tap caskroom/versions
  homebrew_tap:
    name: caskroom/versions
    state: present

- name: Install Browers
  homebrew_cask:
    name: "{{ item }}"
    state: "{{ package_state }}"
  with_items:
    - firefox
    - firefox-developer-edition
    - google-chrome

- name: Install Tunnelblick
  homebrew_cask:
    name: tunnelblick
    state: "{{ package_state }}"

- name: Install Citrix Receiver
  homebrew_cask:
    name: citrix-receiver
    state: "{{ package_state }}"

- name: Install postman
  homebrew_cask:
    name: postman
    state: "{{ package_state }}"

- name: Install OSX productivity tools
  homebrew_cask:
    name: "{{ item }}"
    state: "{{ package_state }}"
  with_items:
    - alfred
    - flux
    - flycut
    - google-hangouts
    - itsycal
    - slack
    - spectacle
    - yakyak
