---
- name: Install GNU utilities
  homebrew:
    name: "{{ item }}"
    install_options: with-default-names
    state: "{{ package_state }}"
  loop:
    - coreutils
    - findutils
    - gnu-tar
    - gnu-sed
    - gawk
    - gnutls
    - gnu-indent
    - gnu-getopt

- name: Install Shell
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - bash
    - tmux

- name: Install iterm2
  homebrew_cask:
    name: iterm2
    state: "{{ package_state_cask }}"

- name: Install shell utilities
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - pstree
    - psgrep
    - screen
    - curl
    - rsync
    - telnet
    - tree
    - watch
    - wget

- name: Tap git-duet/tap
  homebrew_tap:
    name: git-duet/tap
    state: present

- name: Install git and helpers
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - git
    - tig
    - git-duet

- name: Install vim
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - vim
    - neovim

- name: Install additional CLI utilities
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - ack
    - jq
    - httpie
    - lastpass-cli
    - openvpn
    - perl
    - pwgen
    - speedtest-cli
    - vault

- name: Install cloud CLI tools
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - awscli
    - s3cmd

- name: Install build tools
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - autoconf
    - automake

- name: Tap caskroom/versions
  homebrew_tap:
    name: caskroom/versions
    state: present

- name: Install Browers
  homebrew_cask:
    name: "{{ item }}"
    state: "{{ package_state_cask }}"
  loop:
    - firefox
    - firefox-developer-edition
    - google-chrome

- name: Install Tunnelblick
  homebrew_cask:
    name: tunnelblick
    state: "{{ package_state_cask }}"

- name: Install Citrix Tools
  homebrew_cask:
    name: "{{ item }}"
    state: "{{ package_state_cask }}"
  loop:
    - citrix-receiver
    - citrix-workspace

- name: Install postman
  homebrew_cask:
    name: postman
    state: "{{ package_state_cask }}"

- name: Install OSX productivity tools
  homebrew_cask:
    name: "{{ item }}"
    state: "{{ package_state_cask }}"
  loop:
    - alfred
    - flux
    - flycut
    - google-hangouts
    - grandperspective
    - itsycal
    - lastpass
    - slack
    - spectacle
    - yakyak
