---
- name: Install GNU utilities
  homebrew:
    name: "{{ item }}"
    install_options: with-default-names
    state: "{{ package_state }}"
  with_items:
    - coreutils
    - findutils
    - gnu-tar
    - gnu-sed
    - gawk
    - gnutls
    - gnu-indent
    - gnu-getopt

- name: Install Shell
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  with_items:
    - bash
    - tmux

- name: Install iterm2
  homebrew_cask:
    name: iterm2
    state: "{{ package_state }}"

- name: Install shell utilities
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  with_items:
    - pstree
    - psgrep
    - screen
    - curl
    - rsync
    - telnet
    - tree
    - watch
    - wget

- name: Install git and helpers
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  with_items:
    - git
    - tig

- name: Install vim
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  with_items:
    - vim
    - neovim

- name: Install additional utilities
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  with_items:
    - ack
    - jq
    - httpie
    - perl
    - pwgen
    - speedtest-cli
    - vault

- name: Install postman
  homebrew_cask:
    name: postman
    state: "{{ package_state }}"
