---
- name: Javascript
  tags:
    - javascript
    - js
  become: yes
  block:
    - name: Install Nodejs and NPM
      tags:
        - nodejs
        - node
        - npm
      ansible.builtin.package:
        name:
          - nodejs
          - npm
        state: "{{ package_state }}"

    - name: Install Yarn
      tags:
        - yarn
      community.general.npm:
        name: yarn
        global: yes
