---
- name: Install NPM and Bower
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - npm
    - bower

- name: Install Chrome Driver
  homebrew_cask:
    name: chromedriver
    state: "{{ package_state }}"
