---
- name: Install Kubernetes and Helm
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - kubernetes-cli
    - helm

- name: "Install kubectl {{ kubectl_watcher_version }}"
  get_url:
    url: "{{ kubectl_watcher_download_url_osx }}"
    dest: "{{ ansible_env.HOME }}/local/bin/kubectl-{{ kubectl_watcher_version }}"
    mode: 0755
