---
- name: Install Kubernetes and Helm
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - kubernetes-cli
    - kubernetes-helm

- name: "Install kubectl {{ kubectl_watcher_version }}"
  get_url:
    url: "{{ kubectl_watcher_download_url_osx }}"
    dest: "{{ ansible_env.HOME }}/local/bin/kubectl-{{ kubectl_watcher_version }}"
    mode: 0755

- name: "Symlink for kubectl {{ kubectl_watcher_version }}"
  file:
    src: "{{ ansible_env.HOME }}/local/bin/kubectl-{{ kubectl_watcher_version }}"
    dest: "{{ ansible_env.HOME }}/local/bin/kubectl"
    state: link
