---
- name: Brave Browser
  tags:
    - browser
    - brave
    - brave-browser
  become: yes
  block:
    - name: Enable Brave Browser repository
      ansible.builtin.yum_repository:
        name: brave-browser
        file: brave-browser
        description: Brave Browser
        baseurl: https://brave-browser-rpm-release.s3.brave.com/x86_64/
        gpgcheck: yes
        gpgkey: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
        enabled: yes
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Brave Browser
      ansible.builtin.package:
        name: brave-browser
        state: "{{ package_state }}"
