---
- name: Podman
  tags:
    - containers
    - podman
  become: yes
  when: ansible_os_family == 'RedHat'
  block:
    - name: Install Podman
      ansible.builtin.package:
        name:
          - podman
          - podman-compose
        state: "{{ package_state }}"

    - name: "Configure rootless Podman for {{ bootstrap_user }}"
      ansible.builtin.shell: |
        echo {{ bootstrap_user }}
        grep -q {{ bootstrap_user }} /etc/subuid || usermod --add-subuids 10000-75535 {{ bootstrap_user }}
        grep -q {{ bootstrap_user }} /etc/subgid || usermod --add-subgids 10000-75535 {{ bootstrap_user }}
        podman system migrate

    - name: Install podman-docker unless we are installing Docker
      ansible.builtin.package:
        name:
          - podman-docker
        state: "{{ (install_docker) | ternary('absent', package_state) }}"

- name: Docker
  when: install_docker
  tags:
    - containers
    - docker
  become: yes
  block:
    - name: Install Docker
      ansible.builtin.package:
        name:
          - moby-engine
          - docker-compose
        state: "{{ package_state }}"

    - name: "Add {{ bootstrap_user }} to docker group"
      user:
        name: "{{ bootstrap_user }}"
        groups: docker
        append: yes
