---
- name: Install Podman
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - podman

- name: Create Podman Machine
  shell: "podman machine init && podman machine start"
