---
- name: Install Docker
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - docker
    - docker-machine
    - dive

- name: Set Docker to run at login
  shell: "brew services start docker-machine"
