---
- name: "Tools - Fedora"
  tags:
    - tools
  when: ansible_distribution == 'Fedora'
  become: yes
  block:
    - name: Enable bcotton/cherrytree COPR
      community.general.copr:
        state: enabled
        name: bcotton/cherrytree

    - name: Install cherrytree
      ansible.builtin.package:
        name: cherrytree-future
        state: "{{ package_state }}"
