---
- name: Install VirtualBox
  homebrew_cask:
    name: virtualbox
    state: "{{ package_state }}"

- name: Install Vagrant
  homebrew_cask:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - vagrant
