---
- import_tasks: fedora.yaml
  when: ansible_distribution|lower == 'fedora'
  become: yes

- name: Install VSCode extensions
  shell: "code --install-extension {{ item }}"
  tags:
    - vscode
  loop: "{{ vscode_extensions }}"

