---
- name: VSCode
  tags:
    - ide
    - vscode
  become: yes
  block:
    - name: "Package Manager - RedHat Family"
      when: ansible_os_family == 'RedHat'
      become: yes
      block:
        - name: Enable VSCode repository
          ansible.builtin.yum_repository:
            name: code
            file: vscode
            description: Visual Studio Code
            baseurl: https://packages.microsoft.com/yumrepos/vscode
            gpgcheck: yes
            gpgkey: https://packages.microsoft.com/keys/microsoft.asc
            enabled: yes
            state: present

    - name: Install VSCode
      ansible.builtin.package:
        name: code
        state: "{{ package_state }}"

- name: Install VSCode extensions
  become: no
  ansible.builtin.shell: "code --install-extension {{ item }}"
  tags:
    - ide
    - vscode
  loop: "{{ vscode_extensions }}"
