---
- name: Install Atom
  homebrew_cask:
    name: atom
    state: "{{ package_state }}"
  tags:
    - atom

- name: Install VS Code
  homebrew_cask:
    name: visual-studio-code
    state: "{{ package_state }}"
  tags:
    - vscode

- name: Install PyCharm
  homebrew_cask:
    name: pycharm-ce
    state: "{{ package_state }}"
  tags:
    - pycharm

- name: Install IntelliJ
  homebrew_cask:
    name: intellij-idea
    state: "{{ package_state }}"
  tags:
    - intellij
