---

- hosts: all
  roles:
    - role: debug
    - role: packagemanager
    - role: utils
    - role: libraries

- hosts: backup
  roles:
    - role: backup

- hosts: desktop
  tags:
    - desktop
  roles:
    - role: tools
    - role: browsers
    - role: ide
    - role: python

- hosts: media
  roles:
    - role: media

- hosts: dev
  roles:
    - role: golang
    - role: ruby
    - role: javascript
    - role: database
    - role: containers
    - role: kubernetes

- hosts: rstudio
  roles:
    - role: cpp

- hosts: hypervisors
  roles:
    - role: virtualization
