---
- name: Libraries
  tags:
    - lib
  become: yes
  block:
    - name: ZLib
      ansible.builtin.package:
        name:
          - zlib
          - zlib-devel
        state: "{{ package_state }}"
