---
- name: Install pkg-config
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - pkg-config

- name: Install XML libraries
  homebrew:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - libxml2
    - libxslt
    - libxmlsec1
