---
- name: Install Ruby
  dnf:
    name:
      - ruby
      - ruby-devel
      - rubygem-json
    state: "{{ package_state }}"

- name: Install Bundler.
  gem:
    name: bundler
    state: "{{ package_state }}"
    user_install: no
