---
- name: Install Ruby
  dnf:
    name: "{{ item }}"
    state: "{{ package_state }}"
  loop:
    - ruby
    - ruby-devel
    - rubygem-json


- name: Install Bundler.
  gem: 
    name: bundler 
    state: "{{ package_state }}"
    user_install: no
