---
- name: Ruby
  tags:
    - ruby
    - rb
  become: yes
  block:
    - name: Install Ruby
      ansible.builtin.package:
        name:
          - ruby
          - ruby-devel
          - rubygem-json
        state: "{{ package_state }}"

    - name: Install Bundler.
      gem:
        name: bundler
        state: "{{ package_state }}"
        user_install: no

    - name: Install common gems
      community.general.gem:
        name: "{{ item }}"
        state: "{{ package_state }}"
        user_install: no
      loop:
        - bundler
        - json
        - rspec
        - rubocop
        - solargraph
