---
- import_tasks: fedora.yaml
  when: ansible_distribution|lower == 'fedora'
  become: yes

- name: Install common gems
  gem:
    name: "{{ item }}"
    state: "{{ package_state }}"
    user_install: no
  loop:
    - bundler
    - json
    - rspec
    - rubocop
    - solargraph
  become: yes
