---
- name: Ruby
  tags:
    - ruby
    - rb
  become: yes
  block:
    - name: Install Ruby - RedHat Family
      when: ansible_os_family == 'RedHat'
      ansible.builtin.package:
        name:
          - ruby
          - ruby-devel
        state: "{{ package_state }}"

    - name: Install Ruby - Debian Family
      when: ansible_os_family == 'Debian'
      ansible.builtin.package:
        name:
          - ruby
          - ruby-dev
        state: "{{ package_state }}"

    - name: Install Bundler
      community.general.gem:
        name: bundler
        state: "{{ package_state }}"
        user_install: no

    - name: Install common gems
      community.general.gem:
        name: "{{ item }}"
        state: "{{ package_state }}"
        user_install: no
      loop:
        - bundler
        - json
        - rspec
        - rubocop
        - solargraph
