---
- import_tasks: fedora.yaml
  when: ansible_distribution|lower == 'fedora'
  become: yes

- import_tasks: osx.yaml
  when: ansible_os_family|lower == 'darwin'

- import_tasks: watcher.yaml
  when: ansible_os_family|lower == 'darwin'
