---
- name: Install ruby
  homebrew:
    name:
      - ruby
    state: "{{ package_state }}"

- name: Link ruby
  homebrew:
    name:
      - ruby
    state: linked

- name: Install chruby
  homebrew:
    name:
      - chruby
      - ruby-install
    state: "{{ package_state }}"
